### ISSUE TITLE
Support custom enclosure guid element to reference media files

### ISSUE THREAD

**Issue by timpritlove** [astro/prittorrent#33]
This is an alternate solution to #30 

If Bitlove would accept a custom Bitlove enclosure-guid element in a feed, any bitlove-aware feed publishing system could reference media files in Bitlove using a self-chosen GUID.

Example:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:bitlove="http://bitlove.org" version="2.0">
<channel>

    <item>
        <title>Podcast Episode</title>
        <enclosure url="http://example.com/podlove/file/2342/" length="36557482" type="audio/mp4" />
        <bitlove:enclosure-guid>http://example.com/podlove/file/2342/</bitlove:enclosure-guid>
    </item>

</channel>
```

The Bitlove Widget could accept the GUID as a valid URL in the torrentByEnclosure JavaScript function and we're set.

**Comment by astro** [comment]
Thank you very much @timpritlove! This seems to be a much better solution.

**Comment by timpritlove** [comment]
Let us know when you think you have it ready. We'll put it into Podlove Publisher immediately.

**Comment by eteubert** [comment]
I have the Publisher commit ready: https://github.com/podlove/podlove-publisher/commit/ad1b0aa9eabba1ec5a3b3dc9d3fb9efc8bed8218

**Comment by timpritlove** [comment]
Might be worth considering a slightly different namespace if you don't want to spoil "http://bitlove.org" for this and go for something along "http://bitlove.org/api" or "http://bitlove.org/extensions". This would provide the opportunity to place namespace usage documentation under the same URL.

**Comment by astro** [comment]
About to implement this now... why aren't we reusing RSS guid/ATOM id for this? They seem like the appropriate identifier to use. Is that mangled by Feedburner as well?

**Comment by timpritlove** [comment]
The RSS GUID is for the <item>, not the enclosure. Multiple feeds might refer to the same item referring to different enclosures (= MP3, M4A, Vorbis, Opus versions of the same item all carry the same GUID).

However, in the absence of the enclosure-guid you could alternatively accept a standard GUID too.

**Comment by astro** [comment]
Implemented as proposed.

Please test:
```shell
curl "http://api.bitlove.org/by-enclosure.json?guid=podlove-2014-03-13t14:09:09%2b00:00-b45e1d2cabbbccf"
```
(Note the URL-encoded `+`)

**Comment by timpritlove** [comment]
Is there official documentation for this? Did you just implement reference to the episode GUID or is the enclosure-guid element supported too? Can't find the commit covering this...

**Comment by astro** [comment]
Here you go: http://bitlove.org/help/podcaster/api#by-guid

Commits:
* https://github.com/astro/prittorrent/commit/4452d23c13eac11286156b04529cbb115c06c6ba
* https://github.com/astro/prittorrent/commit/6da16f8f61752a986af678de84efb236d728c087
* https://github.com/astro/prittorrent/commit/f4ca709aa86108646978c831094b5ba6cd4dc650
* https://github.com/astro/bitlove-ui/commit/86eb2028a776f201d28f9993660c56d01a64b863
* https://github.com/astro/bitlove-ui/commit/9055d1db83048d34b530569e1031a1aa83f31e94

**Comment by timpritlove** [comment]
So I think this is now <bitlove:guid> which is okay too.

**Comment by astro** [comment]
No, it is an attribute to the enclosure element! (Github swallowed your angle brackets.)

ATOM/RSS id/guid elements of items work as fallback though.

**Comment by timpritlove** [comment]
Ah okay, so ```<enclosure bitlove:guid="**guid**" …>```

**Comment by astro** [comment]
Right.

Is my documentation clear on this?
